version: '3.8'

services:
  backend:
    build: 
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    command: >
      sh -c "python -m prepare || python -m run"

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000